apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yml
  - persistentvolume.yml
  - db-service.yml
  - db-statefulset.yml
  - redis-deployment.yml
  - redis-service.yml
  - chat-deployment.yml
  - chat-service.yml
  - hpa.yml
  - ingress.yml

images:
  - name: werayco/chatdome
    newTag: latest

commonAnnotations:
  env: development
  support-contact: werayco@gmail.com