apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: werayco/chatdome
    newTag: latest

commonAnnotations:
  env: development
  support-contact: werayco@gmail.com