apiVersion: v1
kind: Secret
metadata:
  name: chatdome-secrets
type: Opaque

stringData:
  DATABASE_URL: "postgresql+asyncpg://domeadmin:fXg6jwUyZOt@postgres:5432/dome"
  JWT_SECRET: "OmQhlScwr8PzsdL/3iuXsBjyNDeTSQQdnYmw7xY+KMo="
  POSTGRES_USER: "domeadmin"
  POSTGRES_PASSWORD: "fXg6jwUyZOt"
  POSTGRES_DB: "dome"
  POSTGRES_HOST: "postgres"